### ISSUE TITLE
好像沾喜气一直报错

### ISSUE THREAD

**Issue by liuqiaochi** [iDerekLi/juejin-helper#111]
![image](https://user-images.githubusercontent.com/16871145/226075632-44ad6ac1-e365-4296-82d5-ef102f8e3e64.png)

**Comment by iDerekLi** [comment]
调整一下您的自动化执行时间就好了。具体步骤参见 #110

**Comment by liuqiaochi** [comment]
![image](https://user-images.githubusercontent.com/16871145/227069668-4c1a2c19-35ac-4a19-a4ab-db109acb8a67.png)

已经调了，依然报错
