### ISSUE TITLE
yarn seagold：error

### ISSUE THREAD

**Issue by classfang** [iDerekLi/juejin-helper#112]
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 404".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.

**Comment by ManInTheWind** [comment]
![image](https://user-images.githubusercontent.com/32859126/227160731-3eb3e143-32da-4546-b5ed-79cbcfe37522.png)

**Comment by iDerekLi** [comment]
官方游戏下线 #114
