### ISSUE TITLE
【海底掘金挑战赛】游戏已下线

### ISSUE THREAD

**Issue by CodeFishK** [iDerekLi/juejin-helper#114]
最近海底掘金天天报错，原来是官方下线了这个游戏，具体公告如下：_

> <img width="750" alt="image" src="https://user-images.githubusercontent.com/38446347/227815102-a5e8597c-2975-42d5-89b7-609cff559c9e.png">

**Comment by Tanhahahaha** [comment]
同样的 把代码注释就行了 doge

**Comment by Tanhahahaha** [comment]
> 最近海底掘金天天报错，原来是官方下线了这个游戏，具体公告如下：_
> 
> > <img alt="image" width="750" src="https://user-images.githubusercontent.com/38446347/227815102-a5e8597c-2975-42d5-89b7-609cff559c9e.png"> 同样的 把代码注释就行了 doge

**Comment by iDerekLi** [comment]
根据官方通知，自动化海底掘金游戏已关闭
