### ISSUE TITLE
CheckIn报错

### ISSUE THREAD

**Issue by CodeFishK** [iDerekLi/juejin-helper#122]
**报错如下：**

> **[CheckIn]**
> Process completed with exit code 1.
> **[CheckIn]**
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/38446347/234483305-ea258ba7-68ca-497b-8b22-9872c1b44452.png">

**Comment by IronManStank** [comment]
I met a same problem in running this project in local machine (Debian 6.1.20-2).

**Comment by iDerekLi** [comment]
您失败原因是账号令牌失效了；在掘金平台上重新登陆后，更换新cookies到这里再试试。
