### ISSUE TITLE
收到了掘金站内信警告⚠

### ISSUE THREAD

**Issue by roy-lau** [iDerekLi/juejin-helper#23]
https://juejin.cn/pin/7065954293509160997

![image](https://user-images.githubusercontent.com/22829291/156922128-091b1ab7-a9f6-4f2f-8833-f9a1dc75c325.png)

能不能增加个“社区活跃记录”的功能呢？
比如每天执行actions 的时候顺便访问下掘金首页或者沸点什么的。😁

**Comment by klren0312** [comment]
访问得上无头浏览器了吧

**Comment by iDerekLi** [comment]
好的, 现阶段建议您每日访问一下掘金平台.
近期尝试解决此类问题.

**Comment by roy-lau** [comment]
> 好的, 现阶段建议您每日访问一下掘金平台.
> 
> 近期尝试解决此类问题.

👍👍👍

**Comment by roy-lau** [comment]
> 访问得上无头浏览器了吧
@klren0312 不需要吧！应该是访问几个log开头的接口就行。
![image](https://user-images.githubusercontent.com/22829291/158299983-79aeef08-7af0-428f-acbc-ee7fd4d14d33.png)

**Comment by iDerekLi** [comment]
签到脚本已增加事件埋点, 通过此方式来解决“社区活跃记录”的问题, 尝试Fetch仓库代码.

**Comment by roy-lau** [comment]
> 签到脚本已增加事件埋点, 通过此方式来解决“社区活跃记录”的问题, 尝试Fetch仓库代码.

大佬NB
666666666666
