### ISSUE TITLE
掘金的 cookie 变更了

### ISSUE THREAD

**Issue by roy-lau** [iDerekLi/juejin-helper#29]
我今天早上收到签到邮件，cookie 过期了。更新了cookie后报了如下的错误：
![图片](https://user-images.githubusercontent.com/22829291/164191499-ddff0d3d-92a1-4f63-81d9-edc5818f9b18.png)
对比过cookie后发现有一些字段和值的格式好像有变更，上面报错会不会是掘金修改cookie导致的？大佬什么时候有空适配一下新的cookie 呗！

**Comment by iDerekLi** [comment]
您之前的cookie过期了, 去掘金上重新登录在填写新cookie就行.

**Comment by roy-lau** [comment]
> 您之前的cookie过期了, 去掘金上重新登录在填写新cookie就行.

这次貌似不是的 cookie 过期的问题。我刚刚又退出重新登录了后更新了cookie还是不行。

**Comment by iDerekLi** [comment]
emmm..在我这测试没发现新cookie没有遇到错误现象. 你检查一下看看在复制cookie过程中有没有遗漏字符.

**Comment by roy-lau** [comment]
今天又试了试，莫名奇妙竟然好了 😓
