### ISSUE TITLE
cron !?

### ISSUE THREAD

**Issue by JavaHackSen** [iDerekLi/juejin-helper#58]
冒昧的问一下~就是如果想改一下定时时间要怎么改呀！？
我看cron是40 22 * * *呢！？
请问要怎么改一下呀！？

**Comment by ZiuChen** [comment]
[Cron 表达式](https://cloud.tencent.com/document/product/583/9708)

**Comment by JavaHackSen** [comment]
22不是下午10点嘛~我咋有的懵呢🤐

**Comment by ZiuChen** [comment]
[schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
这里指定的是UTC时间，中国大陆的时间与UTC的时差为+8，故需要设置提前8小时

**Comment by JavaHackSen** [comment]
好的~谢谢，🥳
