### ISSUE TITLE
今天运行checkin出错

### ISSUE THREAD

**Issue by runzhenghengbin** [iDerekLi/juejin-helper#60]
![image](https://user-images.githubusercontent.com/16401077/180672370-98801bfa-9897-4dba-a08e-109fce8ab3e6.png)

**Comment by runzhenghengbin** [comment]
另一个挖矿是正常的。之前都是正常的

**Comment by ZiuChen** [comment]
> 另一个挖矿是正常的。之前都是正常的

手动重新执行一下Action试试

**Comment by runzhenghengbin** [comment]
重试后正常
