### ISSUE TITLE
最后是要新建一个self-hosted吗？？？

### ISSUE THREAD

**Issue by szlgg** [iDerekLi/juejin-helper#61]
![6881658994426_ pic](https://user-images.githubusercontent.com/81397974/181450652-3fe951db-10b4-4165-b380-7e2ca1ecfdab.jpg)

**Comment by iDerekLi** [comment]
不需要，进入Actions标签页把它启用就可以了

**Comment by szlgg** [comment]
> 不用，进入Actions标签页把它启用就可以了

![image](https://user-images.githubusercontent.com/81397974/181662899-264a6dd9-c195-448a-ae6b-80573a821ed1.png)
这样就可以了吗

**Comment by szlgg** [comment]
> 不需要，进入Actions标签页把它启用就可以了

![image](https://user-images.githubusercontent.com/81397974/181663570-69e11848-6557-4a55-bfa3-efb3d1748de2.png)
![image](https://user-images.githubusercontent.com/81397974/181663589-e1593f28-8f77-4765-afad-f3a82b3f9724.png)
![image](https://user-images.githubusercontent.com/81397974/181663622-d3212187-0c9c-4594-a6fe-84c875b034bc.png)
这样就可以了对吗？

**Comment by iDerekLi** [comment]
是的
