### ISSUE TITLE
成长任务考虑加进去吗？

### ISSUE THREAD

**Issue by fadeds** [iDerekLi/juejin-helper#64]

**Comment by fadeds** [comment]
![image](https://user-images.githubusercontent.com/27796945/183369365-d82e8d1d-5851-4442-87fc-b77c5fd04e3e.png)
手动运行checkin没问题，推送没问题
手动运行seagold 推送报错 间隔时间2分钟运行

**Comment by iDerekLi** [comment]
这个问题尝试更新至最新平台Cookie试试

**Comment by fadeds** [comment]
同一个cookie 今天又是checkin报错  seagold没有报错  我改了一下运行时间  checkin 6.30  seagold 6.40 因为checkin运行快  不知道是不是两个脚本同时用cookie 导致的

**Comment by iDerekLi** [comment]
github actions有时候是会出现间接性无法执行，执行时机并不是准确的。
不排除checkin action延迟到和seagold action相同时间执行的情况，但是逻辑上来讲玩游戏并不耽误我签到。
测试两天看看，如果还会发生类似问题，改成用一个工作流串联两个action形式。

**Comment by iDerekLi** [comment]
工程已重构，建议 Fetch 到最新。🥰玩的愉快～
