### ISSUE TITLE
是不是BBQ了。掘金开始检测了。。。多好的一个插件。

### ISSUE THREAD

**Issue by liaopen123** [iDerekLi/juejin-helper#95]
近期检测到掘友存在违规现象，违规版块为：用户中心-每日签到，具体违规现象为：“脚本签到：当日签到，但在稀土掘金双端无活跃记录”，违规次数为：4次。本次为提醒，如本周仍出现违规现象，会暂停掘友账户参与用户中心相关功能一周时间

**Comment by hnnw** [comment]
我也遇到了

**Comment by ZiuChen** [comment]
检查日志里是否有埋点调用成功的提示

**Comment by linxianxi** [comment]
发几个几个浏览文章列表或者沸点的请求，应该就可以了

**Comment by hnnw** [comment]
> 发几个几个浏览文章列表或者沸点的请求，应该就可以了

周一到周五我基本都会打开掘金看下沸点和文章列表，还是受到违规次数7次，难道是累计？

**Comment by linxianxi** [comment]
> > 发几个几个浏览文章列表或者沸点的请求，应该就可以了
> 
> 周一到周五我基本都会打开掘金看下沸点和文章列表，还是受到违规次数7次，难道是累计？

它这个是在北京时间上午06:30，签到。估计是查这个时间段你的接口调用情况。

**Comment by hnnw** [comment]
> > > 发几个几个浏览文章列表或者沸点的请求，应该就可以了
> > 
> > 
> > 周一到周五我基本都会打开掘金看下沸点和文章列表，还是受到违规次数7次，难道是累计？
> 
> 它这个是在北京时间上午06:30，签到。估计是查这个时间段你的接口调用情况。

有这个可能，有其他jy改了时间也被抓到吗

**Comment by ihwf** [comment]
八九点签一样被抓

**Comment by linxianxi** [comment]
要在程序里随机生成一个数，setTimeout 后执行签到。不然都是 6:30 签直接抓。

**Comment by liyk-master** [comment]
他贴出来的问题是有签到但是双端都不活跃，难道再随机阅读下文章

**Comment by iDerekLi** [comment]
近期掘金推送 ”脚本签到“ 系统消息，根据消息原因是 ”当日签到，但在稀土掘金双端无活跃记录“。
但以什么方式算端活跃？目前需要进一步判断

**Comment by fadeds** [comment]
一样，现在我都加了ios自动化 打开浏览器 访问web端的某个文章，定时操作呗

**Comment by fadeds** [comment]
> 要在程序里随机生成一个数，setTimeout 后执行签到。不然都是 6:30 签直接抓。

定时没用，我跑的是加了定时的，一样，我现在就是ios自动化打开浏览器 访问文章

**Comment by liaopen123** [comment]
> 

能否共享一下脚本[斜眼笑]

**Comment by liaopen123** [comment]
> 一样，现在我都加了ios自动化 打开浏览器 访问web端的某个文章，定时操作呗

能否共享一下脚本[斜眼笑]

**Comment by liyk-master** [comment]
试验下，不会封分享下

**Comment by fadeds** [comment]
就是iss里的青龙，ios自动化是自己配的，也需要手机亮屏

**Comment by liuqiaochi** [comment]
这个脚本确实是最好的，希望作者能看看怎么解决避免被警告

**Comment by liuqiaochi** [comment]
> 已添加模拟用户活跃功能！功能在workflow版本v1.7.0中体现, 尝试fetch仓库代码！
> 
> ![模拟用户活跃](https://user-images.githubusercontent.com/24502299/212030485-0be3cf2e-842e-485a-83fb-303d4a9db1ce.png)

大佬牛逼

**Comment by ihwf** [comment]
最稳妥的方法可能是用无头浏览器模拟操作

**Comment by fadeds** [comment]
> 已添加模拟用户活跃功能！功能在workflow版本v1.7.0中体现, 尝试fetch仓库代码！
> 
> ![模拟用户活跃](https://user-images.githubusercontent.com/24502299/212030485-0be3cf2e-842e-485a-83fb-303d4a9db1ce.png)

npm的包有更新吗？我更新一下

**Comment by iDerekLi** [comment]
> 

npm晚些时候更新

**Comment by fadeds** [comment]
> npm晚些时候更新

好的，谢谢

**Comment by iDerekLi** [comment]
> > npm晚些时候更新
> 
> 好的，谢谢

@fadeds npm `juejin-helper@1.7.1` 已发布

### 模拟用户活跃 代码示例
```javascript
const JuejinHelper = require("juejin-helper");

async function run() {
  const juejin = new JuejinHelper();
  await juejin.login("你的掘金Cookie");

  const browser = juejin.browser();

  await browser.open();

  try {
    await browser.visitPage("/");
    console.log("掘金首页：页面访问成功");
  } catch (e) {
    console.log("掘金首页：页面访问失败");
  }

  try {
    await browser.visitPage("/user/center/signin");
    console.log("掘金每日签到：页面访问成功");
  } catch (e) {
    console.log("掘金每日签到：页面访问失败");
  }

  // const page = await browser.visitPage("/");
  // const screenshotBuffer = await page.screenshot(); // 获取页面快照

  await browser.close();

  await juejin.logout();
}
```

**Comment by fadeds** [comment]
![image](https://user-images.githubusercontent.com/27796945/212242611-ce1a9424-8adc-400d-ac18-7d3c07e2f3c8.png)
我加到这里去了，应该是跟你的结构一样的
